### ISSUE TITLE
update to extra-metadata

### ISSUE THREAD

**Issue by kmexter** [arms-mbon/data_release_001#3]
for all of them in GH, in fact
For this one: add zip and csv as a format for the EMOF of COI (had to zip as native was too large)
and update all CSVs:
(2) https://www.iana.org/assignments/media-types/media-types.xhtml --> csv is there listed as text/csv or https://www.iana.org/assignments/media-types/text/csv
 
change fileFormat to encodingFormat
(1) yes, if possible - according to schema.org this is superseded by encodingFormat (https://schema.org/fileFormat)
fileFormat - Schema.org Property
Schema.org Property: fileFormat - Media type, typically MIME format (see IANA site) of the content, e.g. application/zip of a SoftwareApplication binary. In cases where a CreativeWork has several m...

**Comment by cedricdcc** [comment]
with the latest push this was fixed , the ROCrateFix has also been updated to handle more exceptions in the rocrate-metadata.json

**Comment by kmexter** [comment]
grand - can you do that also for data_workspace, code_release_001 and analysis_release_001 (i.e. for all ro-crate forming actions)

will then need to do that also for the ro-crate actions of emo bon....

**Comment by cedricdcc** [comment]
all repos that are from arms mentioned in your previous comment have been fixed by the rocrate action , for some I had to adapt the extra-metadata.json for the rocrate to work, pls double check if all is fine @kmexter

**Comment by kmexter** [comment]
done
